# Generated by Django 3.0.7 on 2020-07-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200704_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_price',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Items'),
        ),
        migrations.AlterField(
            model_name='item_price',
            name='size',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
    ]
