# Generated by Django 3.0.7 on 2020-07-06 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200704_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_ons',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='item_price',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Items'),
        ),
        migrations.AlterField(
            model_name='item_price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
