# Generated by Django 3.0.7 on 2020-07-06 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200706_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_price',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
    ]
