# Generated by Django 3.0.7 on 2020-07-06 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200707_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Menu'),
        ),
    ]
