# Generated by Django 3.0.7 on 2020-07-08 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200707_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_price',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='orders.Items'),
        ),
    ]
