# Generated by Django 3.0.7 on 2020-07-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200722_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
