# Generated by Django 3.0.7 on 2020-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200722_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(related_name='items', to='orders.Item_price'),
        ),
    ]
